# Official documentation at http://goreleaser.com
project_name: transfer
builds:
  - env:
      - CGO_ENABLED=0
    id: "cli"
    binary: transfer
    goos:
      - windows
      - linux
      - darwin
    ldflags:
      - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
      - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
      - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
      - -w
      - -s
  - env:
      - CGO_ENABLED=0
    id: "gui"
    binary: transfer-gui
    main: ./ui/main.go
    goos:
      - windows
      - linux
      - darwin
    ldflags:
      - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
      - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
      - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
      - -w
dist: release
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    id: "cli"
    builds:
      - "cli"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
  - name_template: "transfer-gui-{{ .Os }}-{{ .Arch }}"
    id: "gui"
    builds:
      - "gui"
    replacements:
      darwin: darwin
      linux: linux
      amd64: amd64
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
