# Official documentation at http://goreleaser.com
project_name: transfer
builds:
  - env:
      - CGO_ENABLED=0
    id: "cli"
    binary: transfer
    goos:
      - windows
      - linux
      - darwin
    ignore:
      - goarch: 386
      - goarch: arm64
    ldflags:
      - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
      - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
      - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
      - -w
      - -s
  - env:
      - CGO_ENABLED=0
    id: "transfer-gui"
    binary: transfer-gui
    main: ./ui/main.go
    goos:
      - windows
      - linux
      - darwin
    ignore:
      - goarch: 386
      - goarch: arm64
    ldflags:
      - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
      - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
      - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
      - -w
      - -s
    overrides:
      - goos: window
        ldflags:
          - -H=windowsgui
dist: release
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    id: "cli"
    builds:
      - "cli"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
  - name_template: "transfer-gui-{{ .Os }}-{{ .Arch }}"
    id: "transfer-gui"
    builds:
      - "transfer-gui"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
