name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.0
      - name: Upgrade upx
        run: |
          # try to fix https://github.com/jenkins-zh/jenkins-cli/issues/493
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xvf upx-3.96-amd64_linux.tar.xz
          upx-3.96-amd64_linux/upx -V
          sudo mv upx-3.96-amd64_linux/upx $(which upx)
          upx -V
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release --skip-publish --rm-dist
      - name: Test
        run: |
          make test
